using System.ComponentModel.DataAnnotations;

namespace Sivar.Erp.Core.Domain.Attributes
{
    /// <summary>
    /// Attribute to mark properties as business keys for entity identification
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class BusinessKeyAttribute : Attribute
    {
        /// <summary>
        /// Indicates if this business key must be unique within the company
        /// </summary>
        public bool IsUnique { get; set; } = true;

        /// <summary>
        /// Indicates if this business key is required
        /// </summary>
        public bool IsRequired { get; set; } = true;

        /// <summary>
        /// The scope of uniqueness (Company, Branch, Global)
        /// </summary>
        public BusinessKeyScope Scope { get; set; } = BusinessKeyScope.Company;

        /// <summary>
        /// Display name for the business key
        /// </summary>
        public string? DisplayName { get; set; }

        /// <summary>
        /// Description of the business key
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Format pattern for the business key (regex pattern)
        /// </summary>
        public string? Format { get; set; }

        /// <summary>
        /// Maximum length for the business key
        /// </summary>
        public int MaxLength { get; set; } = 50;

        /// <summary>
        /// Minimum length for the business key
        /// </summary>
        public int MinLength { get; set; } = 1;

        /// <summary>
        /// Whether the business key is auto-generated
        /// </summary>
        public bool IsAutoGenerated { get; set; } = false;

        /// <summary>
        /// Auto-generation pattern (e.g., "DOC-{0:000000}")
        /// </summary>
        public string? AutoGenerationPattern { get; set; }

        /// <summary>
        /// Creates a new BusinessKeyAttribute
        /// </summary>
        public BusinessKeyAttribute()
        {
        }

        /// <summary>
        /// Creates a new BusinessKeyAttribute with display name
        /// </summary>
        /// <param name="displayName">Display name for the business key</param>
        public BusinessKeyAttribute(string displayName)
        {
            DisplayName = displayName;
        }

        /// <summary>
        /// Creates a new BusinessKeyAttribute with display name and scope
        /// </summary>
        /// <param name="displayName">Display name for the business key</param>
        /// <param name="scope">Scope of uniqueness</param>
        public BusinessKeyAttribute(string displayName, BusinessKeyScope scope)
        {
            DisplayName = displayName;
            Scope = scope;
        }

        /// <summary>
        /// Validates the business key value
        /// </summary>
        /// <param name="value">Value to validate</param>
        /// <returns>Validation result</returns>
        public ValidationResult? Validate(object? value)
        {
            if (value == null)
            {
                return IsRequired 
                    ? new ValidationResult($"{DisplayName ?? "Business key"} is required")
                    : ValidationResult.Success;
            }

            var stringValue = value.ToString();
            if (string.IsNullOrWhiteSpace(stringValue))
            {
                return IsRequired 
                    ? new ValidationResult($"{DisplayName ?? "Business key"} cannot be empty")
                    : ValidationResult.Success;
            }

            if (stringValue.Length < MinLength)
            {
                return new ValidationResult(
                    $"{DisplayName ?? "Business key"} must be at least {MinLength} characters long");
            }

            if (stringValue.Length > MaxLength)
            {
                return new ValidationResult(
                    $"{DisplayName ?? "Business key"} cannot exceed {MaxLength} characters");
            }

            if (!string.IsNullOrEmpty(Format))
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(stringValue, Format))
                {
                    return new ValidationResult(
                        $"{DisplayName ?? "Business key"} does not match the required format");
                }
            }

            return ValidationResult.Success;
        }
    }

    /// <summary>
    /// Defines the scope of business key uniqueness
    /// </summary>
    public enum BusinessKeyScope
    {
        /// <summary>
        /// Unique within the company
        /// </summary>
        Company = 1,

        /// <summary>
        /// Unique within the branch
        /// </summary>
        Branch = 2,

        /// <summary>
        /// Globally unique across all companies
        /// </summary>
        Global = 3,

        /// <summary>
        /// Unique within a specific business context
        /// </summary>
        Context = 4
    }
}
