using System.ComponentModel;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Sivar.Erp.Core.Core;
using Sivar.Erp.Core.Infrastructure.Data;
using Sivar.Erp.Core.Modules.Accounting;
using Sivar.Erp.Core.Modules.Documents;
using Sivar.Erp.Core.Modules.Taxes;
using Sivar.Erp.Core.Modules.DataImport;
using Sivar.Erp.Core.Modules.DataImport.Importers;
using Sivar.Erp.Core.Modules.Domain;
using Sivar.Erp.Core.Modules.Domain.Models;
using Sivar.Erp.Core.Demo;

namespace Sivar.Erp.Core.Configuration
{
    /// <summary>
    /// Extension methods for configuring ERP services in the dependency injection container
    /// </summary>
    [Description("Extension methods for configuring ERP services")]
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Adds core ERP services to the DI container with standard configuration
        /// </summary>
        /// <param name="services">The service collection to add services to</param>
        /// <param name="options">Optional configuration options</param>
        /// <returns>The service collection for method chaining</returns>
        [Description("Adds core ERP services to the DI container")]
        public static IServiceCollection AddSivarErpCore(
            this IServiceCollection services,
            ErpCoreOptions? options = null)
        {
            // Configure options
            if (options != null)
            {
                services.Configure<ErpCoreOptions>(opt =>
                {
                    opt.DatabaseProvider = options.DatabaseProvider;
                    opt.DefaultTimeZone = options.DefaultTimeZone;
                    opt.EnablePerformanceLogging = options.EnablePerformanceLogging;
                    opt.EnableAuditLogging = options.EnableAuditLogging;
                    opt.MaxTransactionBatchSize = options.MaxTransactionBatchSize;
                });
            }
            else
            {
                services.Configure<ErpCoreOptions>(opt =>
                {
                    opt.DatabaseProvider = DatabaseProvider.InMemory;
                    opt.DefaultTimeZone = "UTC";
                    opt.EnablePerformanceLogging = true;
                    opt.EnableAuditLogging = true;
                    opt.MaxTransactionBatchSize = 1000;
                });
            }

            // Register core infrastructure
            services.AddScoped<IRepository, InMemoryRepository>();

            // Register business services
            services.AddScoped<IAccountingService, AccountingService>();
            services.AddScoped<IDocumentService, DocumentService>();
            services.AddScoped<ITaxService, TaxService>();
            services.AddScoped<IDataImportService, DataImportService>();
            services.AddScoped<ICsvImportService, CsvImportService>();
            services.AddScoped<CsvValidationService>();

            // Register specialized entity importers
            services.AddScoped<IEntityImporter<IAccount>, AccountImporter>();
            services.AddScoped<IEntityImporter<IBusinessEntity>, BusinessEntityImporter>();
            services.AddScoped<IEntityImporter<ITax>, TaxImporter>();
            services.AddScoped<IEntityImporter<ItemDto>, ItemImporter>();
            services.AddScoped<IEntityImporter<IDocumentType>, DocumentTypeImporter>();

            // Register logging services
            services.AddLogging(builder =>
            {
                builder.AddConsole();
                builder.SetMinimumLevel(LogLevel.Information);
            });

            return services;
        }

        /// <summary>
        /// Adds demo services with embedded test data capabilities
        /// </summary>
        /// <param name="services">The service collection to add services to</param>
        /// <param name="testDataSet">Name of the test data set to use (default: ElSalvador)</param>
        /// <returns>The service collection for method chaining</returns>
        [Description("Adds demo services with embedded test data")]
        public static IServiceCollection AddSivarErpDemo(
            this IServiceCollection services,
            string testDataSet = "ElSalvador")
        {
            // Add core services first
            services.AddSivarErpCore(new ErpCoreOptions
            {
                DatabaseProvider = DatabaseProvider.InMemory,
                EnablePerformanceLogging = true,
                EnableAuditLogging = true
            });

            // Register demo-specific services
            services.AddScoped<ISampleDataGenerator, SampleDataGenerator>();

            // Configure demo options
            services.Configure<DemoOptions>(options =>
            {
                options.TestDataSet = testDataSet;
                options.AutoGenerateData = true;
                options.MaxSampleRecords = 1000;
                options.IncludeTestTransactions = true;
            });

            return services;
        }

        /// <summary>
        /// Adds advanced ERP services with additional features
        /// </summary>
        /// <param name="services">The service collection to add services to</param>
        /// <param name="options">Advanced configuration options</param>
        /// <returns>The service collection for method chaining</returns>
        [Description("Adds advanced ERP services with additional features")]
        public static IServiceCollection AddSivarErpAdvanced(
            this IServiceCollection services,
            AdvancedErpOptions? options = null)
        {
            // Add core services
            services.AddSivarErpCore(options?.CoreOptions);

            // Add advanced services
            if (options?.EnableWorkflowEngine == true)
            {
                // Future: Add workflow engine services
                // services.AddScoped<IWorkflowEngine, WorkflowEngine>();
            }

            if (options?.EnableReporting == true)
            {
                // Future: Add reporting services
                // services.AddScoped<IReportingService, ReportingService>();
            }

            if (options?.EnableNotifications == true)
            {
                // Future: Add notification services
                // services.AddScoped<INotificationService, NotificationService>();
            }

            return services;
        }

        /// <summary>
        /// Adds ERP services for production use with optimized configuration
        /// </summary>
        /// <param name="services">The service collection to add services to</param>
        /// <param name="connectionString">Database connection string</param>
        /// <param name="options">Production configuration options</param>
        /// <returns>The service collection for method chaining</returns>
        [Description("Adds ERP services for production use")]
        public static IServiceCollection AddSivarErpProduction(
            this IServiceCollection services,
            string connectionString,
            ProductionErpOptions? options = null)
        {
            var coreOptions = new ErpCoreOptions
            {
                DatabaseProvider = options?.DatabaseProvider ?? DatabaseProvider.SqlServer,
                DefaultTimeZone = options?.DefaultTimeZone ?? "UTC",
                EnablePerformanceLogging = options?.EnablePerformanceLogging ?? true,
                EnableAuditLogging = options?.EnableAuditLogging ?? true,
                MaxTransactionBatchSize = options?.MaxTransactionBatchSize ?? 5000
            };

            services.AddSivarErpCore(coreOptions);

            // Configure for production
            services.Configure<ErpCoreOptions>(opt =>
            {
                opt.ConnectionString = connectionString;
            });

            // Future: Replace in-memory repository with actual database repository
            // services.AddScoped<IRepository, SqlServerRepository>();

            return services;
        }
    }

    /// <summary>
    /// Core configuration options for the ERP system
    /// </summary>
    [Description("Core configuration options for the ERP system")]
    public class ErpCoreOptions
    {
        /// <summary>
        /// Database provider to use
        /// </summary>
        [Description("Database provider to use")]
        public DatabaseProvider DatabaseProvider { get; set; } = DatabaseProvider.InMemory;

        /// <summary>
        /// Database connection string (for non-InMemory providers)
        /// </summary>
        [Description("Database connection string")]
        public string? ConnectionString { get; set; }

        /// <summary>
        /// Default time zone for the system
        /// </summary>
        [Description("Default time zone for the system")]
        public string DefaultTimeZone { get; set; } = "UTC";

        /// <summary>
        /// Enable performance logging
        /// </summary>
        [Description("Enable performance logging")]
        public bool EnablePerformanceLogging { get; set; } = true;

        /// <summary>
        /// Enable audit logging
        /// </summary>
        [Description("Enable audit logging")]
        public bool EnableAuditLogging { get; set; } = true;

        /// <summary>
        /// Maximum number of transactions to process in a single batch
        /// </summary>
        [Description("Maximum number of transactions to process in a single batch")]
        public int MaxTransactionBatchSize { get; set; } = 1000;

        /// <summary>
        /// Enable automatic tax calculations
        /// </summary>
        [Description("Enable automatic tax calculations")]
        public bool EnableAutomaticTaxCalculation { get; set; } = true;

        /// <summary>
        /// Default currency code
        /// </summary>
        [Description("Default currency code")]
        public string DefaultCurrencyCode { get; set; } = "USD";
    }

    /// <summary>
    /// Demo-specific configuration options
    /// </summary>
    [Description("Demo-specific configuration options")]
    public class DemoOptions
    {
        /// <summary>
        /// Name of the test data set to use
        /// </summary>
        [Description("Name of the test data set to use")]
        public string TestDataSet { get; set; } = "ElSalvador";

        /// <summary>
        /// Automatically generate sample data on startup
        /// </summary>
        [Description("Automatically generate sample data on startup")]
        public bool AutoGenerateData { get; set; } = true;

        /// <summary>
        /// Maximum number of sample records to generate
        /// </summary>
        [Description("Maximum number of sample records to generate")]
        public int MaxSampleRecords { get; set; } = 1000;

        /// <summary>
        /// Include test transactions in sample data
        /// </summary>
        [Description("Include test transactions in sample data")]
        public bool IncludeTestTransactions { get; set; } = true;

        /// <summary>
        /// Include test documents in sample data
        /// </summary>
        [Description("Include test documents in sample data")]
        public bool IncludeTestDocuments { get; set; } = true;
    }

    /// <summary>
    /// Advanced feature configuration options
    /// </summary>
    [Description("Advanced feature configuration options")]
    public class AdvancedErpOptions
    {
        /// <summary>
        /// Core ERP options
        /// </summary>
        [Description("Core ERP options")]
        public ErpCoreOptions? CoreOptions { get; set; }

        /// <summary>
        /// Enable workflow engine
        /// </summary>
        [Description("Enable workflow engine")]
        public bool EnableWorkflowEngine { get; set; }

        /// <summary>
        /// Enable reporting services
        /// </summary>
        [Description("Enable reporting services")]
        public bool EnableReporting { get; set; }

        /// <summary>
        /// Enable notification services
        /// </summary>
        [Description("Enable notification services")]
        public bool EnableNotifications { get; set; }

        /// <summary>
        /// Enable integration services
        /// </summary>
        [Description("Enable integration services")]
        public bool EnableIntegrations { get; set; }
    }

    /// <summary>
    /// Production-specific configuration options
    /// </summary>
    [Description("Production-specific configuration options")]
    public class ProductionErpOptions
    {
        /// <summary>
        /// Database provider for production use
        /// </summary>
        [Description("Database provider for production use")]
        public DatabaseProvider DatabaseProvider { get; set; } = DatabaseProvider.SqlServer;

        /// <summary>
        /// Default time zone for production
        /// </summary>
        [Description("Default time zone for production")]
        public string DefaultTimeZone { get; set; } = "UTC";

        /// <summary>
        /// Enable performance logging in production
        /// </summary>
        [Description("Enable performance logging in production")]
        public bool EnablePerformanceLogging { get; set; } = true;

        /// <summary>
        /// Enable audit logging in production
        /// </summary>
        [Description("Enable audit logging in production")]
        public bool EnableAuditLogging { get; set; } = true;

        /// <summary>
        /// Maximum transaction batch size for production
        /// </summary>
        [Description("Maximum transaction batch size for production")]
        public int MaxTransactionBatchSize { get; set; } = 5000;

        /// <summary>
        /// Enable database connection pooling
        /// </summary>
        [Description("Enable database connection pooling")]
        public bool EnableConnectionPooling { get; set; } = true;

        /// <summary>
        /// Maximum number of database connections in pool
        /// </summary>
        [Description("Maximum number of database connections in pool")]
        public int MaxConnectionPoolSize { get; set; } = 100;
    }

    /// <summary>
    /// Supported database providers
    /// </summary>
    [Description("Supported database providers")]
    public enum DatabaseProvider
    {
        /// <summary>
        /// In-memory database for demos and testing
        /// </summary>
        [Description("In-memory database for demos and testing")]
        InMemory = 1,

        /// <summary>
        /// SQL Server database
        /// </summary>
        [Description("SQL Server database")]
        SqlServer = 2,

        /// <summary>
        /// PostgreSQL database
        /// </summary>
        [Description("PostgreSQL database")]
        PostgreSQL = 3,

        /// <summary>
        /// MySQL database
        /// </summary>
        [Description("MySQL database")]
        MySQL = 4,

        /// <summary>
        /// SQLite database
        /// </summary>
        [Description("SQLite database")]
        SQLite = 5
    }
}